workflows:
  ios-adhoc:
    name: iOS AdHoc Build
    environment:
      ios_signing:
        provisioning_profiles:
          - name: Joe_iPhone
            distribution_type: ad_hoc
        certificates:
          - path: certificates/ios_distribution.p12
            password: B@ckfl1p!23
        targets:
          com.tribe.parentportal:
            provisioning_profile: Joe_iPhone
            certificate: certificates/ios_distribution.p12

    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web files
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios

    artifacts:
      - build/ios/ipa/*.ipa