workflows:
  ios-adhoc:
    name: iOS AdHoc Build
    environment:
      ios_signing:
        targets:
          App:
            provisioning_profile: Joe_iPhone
            certificate: Adhoc_ParentPortal
            certificate_password: "B@ckfl1p!23"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web files
        script: npm run build
      - name: Sync with Capacitor
        script: npx cap sync ios

    artifacts:
      - build/ios/ipa/*.ipa
