workflows:
  ios-adhoc:
    name: iOS AdHoc Build
    environment:
      groups:
        - p12
      ios_signing:
        provisioning_profiles:
          - name: Joe_iPhone
            distribution_type: ad_hoc
        certificates:
          - name: Adhoc_ParentPortal
            password: $P12_PASSWORD

    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web files
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios

    artifacts:
      - build/ios/ipa/*.ipa
