workflows:
  ios-adhoc:
    name: iOS AdHoc Build
    environment:
      vars:
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
      ios_signing:
        use_target_signing: false
        provisioning_profiles:
          - name: Joe_iPhone
        certificates:
          - name: Adhoc_ParentPortal
            password: "B@ckfl1p!23"

    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web files
        script: npm run build
      - name: Sync with Capacitor
        script: npx cap sync ios

    artifacts:
      - build/ios/ipa/*.ipa