workflows:
  ios-adhoc:
    name: iOS AdHoc Build
    environment:
      vars:
        APP_ID: "com.joewinston.parentportal"
      ios_signing:
  provisioning_profiles:
    - name: Joe_iPhone
      distribution_type: ad_hoc
  certificates:
    - path: certificates/ios_distribution.p12
      password: B@ckfl1p!23
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web files
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
    artifacts:
      - build/ios/ipa/*.ipa
