workflows:
  ios-adhoc:
    name: iOS AdHoc Build
    environment:
      ios_signing:
        targets:
          com.tribe.parentportal:
            distribution_type: ad_hoc
            provisioning_profile: Joe_iPhone
            certificate: Adhoc_ParentPortal
            certificate_password: B@ckfl1p!23

    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web files
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios

    artifacts:
      - build/ios/ipa/*.ipa
